// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aovfjzwcucmqjpgxelqf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFvdmZqendjdWNtcWpwZ3hlbHFmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA4MzA4MDIsImV4cCI6MjA1NjQwNjgwMn0.Qi3qM17oZSVMNNmy2CXZabXBD7uyaD_-oCf7hz56Gg8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);